on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Spécifiez la version de Node.js si nécessaire
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli
    
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: ng build --configuration=production
